markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://oneleaf.me
name: OneLeaf.me
author: unblue
email: fangby@163.com
duoshuo: oneleaf
pygments: true
safe: true
paginate: 20
about: "about"
